2024-06-05 06:21:50 INFO - {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 66603c3ccb78d0d28dcab8cb, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-ykxdvvh-shard-00-00.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-ykxdvvh-shard-00-01.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-ykxdvvh-shard-00-02.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66603c3ccb78d0d28dcab8cb"}, "remainingTimeMS": 29}
2024-06-05 06:21:50 INFO - {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 66603c3ccb78d0d28dcab8cb, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-ykxdvvh-shard-00-00.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-ykxdvvh-shard-00-01.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-ykxdvvh-shard-00-02.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66603c3ccb78d0d28dcab8cb"}, "remainingTimeMS": 29}
2024-06-05 06:21:56 ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message to delete not found
2024-06-05 06:21:56 ERROR - Exception traceback:
Traceback (most recent call last):
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/__init__.py", line 1215, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/__init__.py", line 8449, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdul/Desktop/group_bot/Bot/groups/locks.py", line 89, in check_and_delete_messages
    bot.delete_message(group_id, message.message_id)
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/__init__.py", line 1924, in delete_message
    return apihelper.delete_message(self.token, chat_id, message_id, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/apihelper.py", line 1412, in delete_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message to delete not found

